# 1. Altera para salvar em arquivo (pasta 'db' no seu projeto)
spring.datasource.url=jdbc:h2:file:./db/myfinance_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# 2. Muda para 'update' (para ele NÃO apagar seus dados ao reiniciar)
spring.jpa.hibernate.ddl-auto=update

# 3. Desativa o import.sql automático
# Como o banco agora é permanente, se deixar ligado, ele tentará criar 
# o usuário Nadson toda vez e dará erro de e-mail duplicado.
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false